name: Publish Package

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  publish:
    # prevents this action from running on forks
    if: github.repository == 'vexip-ui/nuxt'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - name: Install deps
        run: pnpm install

      - name: Prepare
        run: pnpm dev:prepare

      - name: Build
        run: pnpm run build

      - name: Publish package
        run: pnpm run publish:ci ${{ github.ref_name }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_OPTIONS: --max-old-space-size=4096
